# .github/workflows/release.yaml

name: Run Test on Push
on:
  push:
          
jobs:
  run_test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install Dependencies
        run: |
          cd src
          go get fl
          cd ..

      - name: Run Linux Test
        run: |
          cd src
          go test -v ./...
          cd ..
